"""Add phone number field to users table

Revision ID: eff9b7c193f6
Revises: 7445e0329691
Create Date: 2023-06-16 12:36:25.045121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff9b7c193f6'
down_revision = '7445e0329691'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=18), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_table('oauth_clients_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requested_scope', sa.String(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_clients_users_id'), 'oauth_clients_users', ['id'], unique=False)
    op.drop_constraint('oauth_clients_uses_client_id_fkey', 'oauth_clients_uses', type_='foreignkey')
    op.create_foreign_key(None, 'oauth_clients_uses', 'oauth_clients', ['client_id'], ['id'])
    op.add_column('user_sessions', sa.Column('geo_country', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=18), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    op.drop_column('user_sessions', 'geo_country')
    op.drop_constraint(None, 'oauth_clients_uses', type_='foreignkey')
    op.create_foreign_key('oauth_clients_uses_client_id_fkey', 'oauth_clients_uses', 'users', ['client_id'], ['id'])
    op.drop_index(op.f('ix_oauth_clients_users_id'), table_name='oauth_clients_users')
    op.drop_table('oauth_clients_users')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
