name: Black

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Black Check
      uses: jpetrucciani/black-check@21.12b0
      with:
        path: "src/api"
