name: Test Coveralls

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Unit tests
        run: make test

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          # The `GITHUB_TOKEN` or `COVERALLS_REPO_TOKEN`.
          # Default: ${{ github.token }}
          # github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          # Set to `true` if you are using parallel jobs, then use `parallel-finished: true` for the last action.
          # Default: false
          parallel: true
          # Set to `true` for the last action when using `parallel: true`.
          # Default: false
          # parallel-finished: ""
          # A name to identify the current job. This is useful in combination with `parallel: true`.
          # Default: null
          flag-name: "Test Coverage (Unit Tests)"
          # A sub-directory in which coverage was executed.
          # Default: '.'
          #base-path: "."
          # Set to true to increase logger verbosity.
          # Default: false
          # debug: false

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel-finished: true
