name: Deploy in staging

on:
  workflow_dispatch:
  push:
    branches: [dev]
    paths:
      - "src/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy in staging
    environment: Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy on staging server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          passphrase: ${{ secrets.DEPLOY_SSH_PASSPHRASE }}
          key: ${{ secrets.DEPLOY_SSH_SECRET }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          script: |
            bash /srv/florgon/scripts/deploy/apis/api/staging.sh
