name: Formatters (Black, isort)

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Formatters
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: pip install --upgrade pip
        working-directory: "src/api/"
      - name: Install formatters
        run: pip install "black<23" isort==5.10.1
        working-directory: "src/api/"
      - name: Black format.
        run: black --diff --check $(git ls-files '*.py')
        working-directory: "src/api/"
      - name: ISort format.
        working-directory: "src/api/"
        run: isort --check-only --profile black .
