name: Linters
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Upgrade pip
      run: pip install --upgrade pip
      working-directory: "src/api/"
    - name: Install linters
      run: pip install "black<23" pylint==v3.0.0a3 mypy==v0.902
      working-directory: "src/api/"
    - name: Black
      run: black --diff --check $(git ls-files '*.py')
      working-directory: "src/api/"
    - name: PyLint
      run: pylint --disable=all --enable=unused-import $(git ls-files '*.py')
      working-directory: "src/api/"
    - name: MyPy
      working-directory: "src/api/"
      run: mypy --strict $(git ls-files '*.py')
    
