name: Linters
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: pip install --upgrade pip
        working-directory: "src/api/"
      - name: Install linters
        run: pip install "black<23" pylint==v3.0.0a3 mypy==v0.902
        working-directory: "src/api/"
      - name: Black
        run: black --diff --check $(git ls-files '*.py')
        working-directory: "src/api/"
      - name: PyLint
        run: pylint --disable=duplicate-code --disable=too-few-public-methods --disable=too-many-arguments --disable=too-many-locals --disable=too-many-return-statements --disable=trailing-whitespace --disable=invalid-name --disable=fixme --disable=consider-using-sys-exit --disable=import-error --disable=line-too-long $(git ls-files '*.py')
        working-directory: "src/api/"
      - name: MyPy
        working-directory: "src/api/"
        run: mypy $(git ls-files '*.py') || true
