name: Tests (PyTest)

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v3
      - name: Build containers (Docker-Compose)
        working-directory: ./src
        run: docker-compose up -d --build
      - name: Check docker containers
        working-directory: ./src
        run: docker ps -a
      - name: Wait for start
        run: sleep 5
      - name: Check docker containers (After wait for start)
        working-directory: ./src
        run: docker ps -a
      - name: Ping web server.
        run: curl http://localhost/utils.getServerTime
      - name: Unit tests (PyTest)
        working-directory: ./src/api/app
        run: docker exec florgon-api_server_1 pytest .
