name: Auto tests

on:
  pull_request:
    branches: ["main", "dev", "staging"]
  workflow_dispatch:
  push:
    branches: ["main", "dev", "staging"]
    paths:
      - "src/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Auto-tests
    steps:
      - uses: actions/checkout@v3
      - name: Build containers
        working-directory: ./src
        run: docker-compose -f ./docker-compose-testing.yml up -d --build
      # TODO: Rework with proper server startup awaiting.
      - name: Wait for start
        run: sleep 5
      - name: Check docker containers
        run: docker ps -a
      - name: Display startup logs
        run: docker logs florgon-api_server_1
      - name: Ping web server.
        run: curl --connect-timeout 45 --max-time 75 http://localhost/utils.getServerTime || true
      - name: Display ping logs
        run: docker logs florgon-api_server_1
      - name: Tests (PyTest, Coverage)
        working-directory: ./src/api/app
        run: docker exec florgon-api_server_1 pytest --cov=app .
